name: Pulse
description: "A creative Social Media Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.3
  flutter_svg: ^1.0.3
  image_picker: ^0.8.7+3 
  permission_handler: ^10.2.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.0
  # sign_in_with_apple: ^3.0.0
  intl: ^0.17.0
  camera: ^0.10.4
  path_provider: ^2.0.12
  video_player: ^2.4.5
  chewie: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/appImages/HomeImage.jpg
    - assets/appImages/icon/icon.png
    - assets/appImages/icon/iphone.png
    - assets/appImages/icon/google.png
    - assets/appImages/icon/apple.png
    - assets/appImages/icon/facebook.png
    - assets/appImages/emptyProfile.jpg
    - assets/appImages/icon/chat_icon.png

  # Add your custom fonts here
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
